### ISSUE TITLE
If PlexHome is enabled this doesn't work.

### ISSUE THREAD

**Issue by onedr0p** [phillipj/node-plex-api#1]
First off, thanks for the library. 

I'm having one problem, I'm getting a "401 Unauthorized" as a response when trying to use it.

I've read here..
https://forums.plex.tv/index.php/topic/72552-plexwatch-plex-notify-script-send-push-alerts-on-new-sessions-and-stopped/?p=774335 
..that this is because of PlexHome. I'll look into adding support for PlexHome / PlexPass users but my knowledge of Node isn't the best. Any help would be appreciated, my nodejs skills are young.

A start would be to get the auth token:
```javascript
	var authString = plexUser + ':' + plexPassword;
	var buffer = new Buffer(authString.toString(), 'binary');
	var auth = 'Basic ' + buffer.toString('base64');

	var identifier = uuid.v4();
	var platform = os.platform();
	var release = os.release();

	var options = {
		url: 'https://plex.tv/users/sign_in.xml',
		headers: {
			'Authorization': auth,
			'X-Plex-Client-Identifier': identifier,
			'X-Plex-Product': 'App',
			'X-Plex-Version': '1.0',
			'X-Plex-Device': 'App',
			'X-Plex-Platform': platform,
			'X-Plex-Platform-Version': release,
			'X-Plex-Provides': 'controller'
		}
	};
	// Do a POST request and get the authentication-token from the XML
```

Then passing the auth token to the header on the requests:
```javascript
	//instead of XML why not just force a json response?	
	var headers = {"Accept": "application/json"}; 

	if (authToken != '') {
		headers["X-Plex-Token"] = authToken;
	}

	if (plexUser != '') {
		headers["X-Plex-Username"] = plexUser;
	}

	// Send request
	var options = {
		url: 'http://localhost:32400/library/onDeck',
		headers: headers
	};

	// Do a GET request and return the json w/o converting the XML
```

Thanks for any help.

**Comment by phillipj** [comment]
Hi @onedr0p,

thanks for reporting this issue. Really appreciate the investigation you have done already and your proposed solution! I have to get this reproduced with PlexHome before looking into what changes has to be done this project. I'll keep you updated :)

**Comment by onedr0p** [comment]
Looks good so far @phillipj 

I was working on my own integration using your project but I really like how to separated out the auth logic from the API.

I am working on a page where the person would input their username / password for plex, the library would then authenticate it, or notify on error. If it the authentication passes I'm hoping to get it written to a config file to be used again.

I tried taking this route:

Calling the class:
routes/index.js
```javascript
var client = new plex({
	hostname: config.plexHost,
	port: config.plexPort,
	username: config.plexUser,
	password: config.plexPassword,
	token: config.plexAuthToken
});
```

I figured passing in the auth token might be a good idea, because then you don't have to authenticate every time you make a request, just call the below authenticate method again on fail. However, I am not sure if this is the right way to accomplish this.

api.js - class init
```javascript
/**
 * [Plex description]
 * @param {[object]}
 */
function Plex (params) {
	this.hostname = params.hostname;
	this.port = params.port || PLEX_SERVER_PORT;
	this.username = params.username;
	this.password = params.password;
	this.token = params.token;
	
        // Possibly authenticate using the authenticate method

	this.serverUrl = "http://" + this.hostname + ":" + this.port;
}
```

api.js - authenticate method
```javascript
Plex.prototype.authenticate = function(username, password) {
	var deferred = Q.defer();

	// console.log(this.username, this.password);

    var buffer = new Buffer(username + ':' + password, 'binary');
    var authBasic = 'Basic ' + buffer.toString('base64');
    var platform = os.platform();
    var release = os.release();

	var options = {
	    url: PLEX_LOGIN_URL,
        headers: {
            'Authorization': authBasic,
            'X-Plex-Client-Identifier': 'e48fee4f-8c21-4826-9f86-7aa0b6963a18',
            'X-Plex-Product': 'App',
            'X-Plex-Version': '1.0',
            'X-Plex-Device': 'App',
            'X-Plex-Platform': platform,
            'X-Plex-Platform-Version': release,
            'X-Plex-Provides': 'controller'
        }
	};

	// Return a promise of out auth token
	request.post(options, function(error, response, xml) {
		if (error) {
			return deferred.reject(error);
		}
		console.log(xml);

		var authTokenRegex = /<authentication-token>(.+?)<\/authentication-token>/ig;
		var token = authTokenRegex.exec(xml);

		console.log(token[1]);

		deferred.resolve(token[1]);
	});

	return deferred.promise;
}
```

I'm really looking forward to your take on it as you seem like you know a lot on node.

Thanks :D

**Comment by phillipj** [comment]
Nice, thanks for sharing! Glad this module is of some use out there :)

My first shot will perform authentication whenever the Plex Server responds with a 401 status code. The auth token will be cached in the PlexAPI-instance, preventing the need to authenticate on **every** Plex Server request.

Caching the auth token to a file sounds like a good idea.. Might be an improvement after getting the most basic auth support up-n-running.

**Comment by phillipj** [comment]
I just added the authentication bit needed for PlexHome into the core of this module now. Which means I'm getting ready to publish v2.0.0. Would you like to test / verify that it actually works with PlexHome @onedr0p?

```bash
$ npm install phillipj/node-plex-api#v2.0.0-0
```
and change the way you are instantiating the PlexAPI client as described in the soon-to-be Readme: https://github.com/phillipj/node-plex-api/blob/feature/plexhome-support/Readme.md

**Comment by onedr0p** [comment]
I will give it a shot tonight when I'm out of work. Looking through your code I like how you handled everything, especially how you handled the auth and taking my way of passing in the options thru a object. I'll report back soon!

**Comment by phillipj** [comment]
Woohoo, thanks for testing this @onedr0p! Sorry about the late reply, didnt notice your edit there... I'll release v2.0 within a few days :)
