### ISSUE TITLE
getting error: 'constuctor port argument is deprecated, use an options object instead'

### ISSUE THREAD

**Issue by tamaker** [phillipj/node-plex-api#101]
I'm trying to run basic tests with the npm module, connecting to my local plex server, authenticating, etc. 

the code I'm using is below (running on a local node.js install from mac book pro)

the error I get is "PlexAPI constuctor port argument is deprecated, use an options object instead.".  then I get timed out ( connect ETIMEDOUT ).

Code I'm running:

`var PlexAPI = require("plex-api");`
`require('dotenv').config();`
`const credentials = require('plex-api-credentials');`
 
`const userAndPass = credentials({`
`    username: process.env.PLEX_AUTH.split(',')[0],`
`    password: process.env.PLEX_AUTH.split(',')[1]`
`});`
 
`const client = new PlexAPI({`
`    hostname: '192.168.1.2',`
`    authenticator: userAndPass`
`}, function(err, res){`
`    if (err){ console.log(err) }`
`    console.log(res)`
`});`
 
`client.query("/").then(function (result) {`
`    console.log("%s running Plex Media Server v%s",`
`        result.friendlyName,`
`        result.version);`
 
`    // array of children, such as Directory or Server items`
`    // will have the .uri-property attached`
`    console.log(result._children);`
`}, function (err) {`
`    console.error("Could not connect to server", err);`
`});`

**Comment by DrEVILish** [comment]
Your problem lies with your attempted callback. The PlexAPI doesn't handle callbacks. It's looking for a PORT number where you have your function.

Below would be correct.

```
const client = new PlexAPI({
hostname: '192.168.1.2',
authenticator: userAndPass
});
```

**Comment by phillipj** [comment]
@tamaker did you figure this out with @DrEVILish's help?
