### ISSUE TITLE
Security Issue with plex server

### ISSUE THREAD

**Issue by jeremykenedy** [phillipj/node-plex-api#107]
Hello,

First off, I love Plex and the hard work you all do!

I do not see a repo for the server so I am unsure where to open this issue.

I discovered a security vulnerability and I want to bring it to your attention. 

I do not want to post details publicly.

Please contact me at jeremykenedy@gmail.com and I can send you details.

Thank you again! 

~ Jeremy

**Comment by phillipj** [comment]
Hi Jeremy,

thanks for getting in touch!

To be sure I understand you correctly, is this related the actual plex server itself or this npm package?

**Comment by jeremykenedy** [comment]
Hi @phillipj,

Thank you for responding :)

Yes, it is with the server no the npm package.

Thank you again!

Jeremy
