### ISSUE TITLE
client.find returning undefined

### ISSUE THREAD

**Issue by petersem** [phillipj/node-plex-api#111]
I'm trying to use the client.find() function, but I'm getting: `Cannot read property 'filter' of undefined`, when I _expect_ to get an array of directories back.

Here is an example of my code to replicate this:

```javascript
PlexODCheck(){
  let ms = new pms({
    plexHTTPS: this.settings.plexHTTPS,
    plexIP: this.settings.plexIP,
    plexPort: this.settings.plexPort,
    plexToken: this.settings.plexToken,
  });

  ms.client.find("/library/sections", {type: "movie"}).then(
    function (result) {
      // list directory objects
      for (let d=0; d < result.MediaContainer.size; d++){
        console.log(result.MediaContainer.Directory[d]);
      }
      return;
    },
    function (err) {
      let now = new Date();
      console.log(now.toLocaleString() + " *On-demand: " + err);
  });
}
```
Looking through your API, I wonder if this related to the use of `result._children` and if, in fact, this was related to old Plex data structures that no longer exist in the current version. Here is the code of yours that I was looking at:

```javascript
PlexAPI.prototype.find = function find(options, criterias) {
    if (typeof options === 'string') {
        // Support old method of only supplying a single `url` parameter
        options = { uri: options };
    }
    if (options.uri === undefined) {
        throw new TypeError('Requires uri parameter');
    }

    return this.query(options).then(function (result) {
        var children = result._children || result.MediaContainer.Server;
        return filterChildrenByCriterias(children, criterias);
    });
};
```

I've only been learning Node for four weeks, so please accept my apologies if this is not a bug, but just my terrible code. :)

**Comment by hkjasf687261gh** [comment]
I'm having the same issue with Plex version `1.21.3.4021-5a0a3e4b2`

Updating the children variable to include `result.MediaContainer.Directory` fixes the issue for me

```js
return this.query(options).then(function (result) {
        var children = result._children || result.MediaContainer.Server || result.MediaContainer.Directory;
        return filterChildrenByCriterias(children, criterias);
    });
```

**Comment by dmytro-shchurov** [comment]
The fix with `|| result.MediaContainer.Directory` does not work with other entries than `sections`. For example `find('/')` returns
```
0: {key: "sections", title: "Library Sections"}
1: {key: "recentlyAdded", title: "Recently Added Content"}
2: {key: "onDeck", title: "On Deck Content"}
```
No `recentlyAdded` nor `onDeck` queries work. The same error.

**Comment by hkjasf687261gh** [comment]
I've updated my MR with more MediaContainer children that were required for different queries,

**Comment by petersem** [comment]
thanks mate
