### ISSUE TITLE
Still compatible with latest Plex versions?

### ISSUE THREAD

**Issue by MMeldrum** [phillipj/node-plex-api#115]
Hi,

I'm trying to retrieve data from my Plex server (v1.24.3.5033) but consistently get errors when the Plex response is parsed.

For example, this request:
```
client.find("/library/recentlyAdded").then(function (directories) {
    console.log(`directories: ${JSON.stringify(directories)}`);
}, function (err) {
    console.error("Script error - ", err);
});
```

results in:

```
Script error -  TypeError: Cannot read properties of undefined (reading 'filter')
    at filterChildrenByCriterias (/Users/xxxxxx/IdeaProjects/node-plex/node_modules/plex-api/lib/api.js:314:21)
    at /Users/xxxxxx/IdeaProjects/node-plex/node_modules/plex-api/lib/api.js:147:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It looks like the problem is that the `find` function is expecting a key that doesn't exist.  It is looking for `result.MediaContainer.Directory`:

```
PlexAPI.prototype.find = function find(options, criterias) {
    if (typeof options === 'string') {
        // Support old method of only supplying a single `url` parameter
        options = { uri: options };
    }
    if (options.uri === undefined) {
        throw new TypeError('Requires uri parameter');
    }

    return this.query(options).then(function(result) {
        var children = result._children || result.MediaContainer.Directory; //    <-- here
        return filterChildrenByCriterias(children, criterias);
    });
};
```

The actual response is:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/597637/144863528-447c36a9-e161-474b-b4ea-93f066dc2d18.png">

Finally, changing the following line:

```var children = result._children || result.MediaContainer.Directory;```

to 

```var children = result._children || result.MediaContainer.Metadata;```

...seems to fix it.

Has the Plex response structure changed?  (Edit: I see it has changed in the past, but the response I receive from Plex seems different again.)

**Comment by phillipj** [comment]
Hi there @MMeldrum!

Thanks for the elaborate report and suggestion 👍🏻

I'll be honest and say I don't have a running Plex system anymore, so I have no way of confirming this.. But I wouldn't be surprised if there has been changes to the structure, as we've seen that happen historically.

What sounds like a viable option to try going forward, is to combine what you've found is the current behaviour, with what you're suggesting:

```js
var children = result._children || result.MediaContainer.Directory || result.MediaContainer.Metadata;
```

That's a backward compatible change which I'd be pretty happy to merge.

Have you confirmed what's _inside_ `.Metadata` is as expected tho? Or will things just blow up further down the line as there's something totally unexpected inside `.Metadata`?

**Comment by MMeldrum** [comment]
Hi @phillipj,

Thanks for the response.  I've confirmed that what's inside `.Metadata` seems to be as expected for my purposes, but I'll see if I can find any differences in the data deeper inside.  (It really is a shame that the Plex devs don't document their API response.)

I was going to suggest that I might write some tests to verify that the response structure hasn't changed but, of course, that would need a Plex instance to integrate with.  I guess I could write a test that takes a Plex URL as a parameter. 🤔  It wouldn't run on every build, but it would be available for manual checks.

I'll see what free time I have during the Christmas break, and raise a PR either with just the above change, or the change plus some tests.

**Comment by MMeldrum** [comment]
Hello again.  I was all set to raise a PR when I noticed [this](https://github.com/phillipj/node-plex-api/pull/114) existing PR which covers my change and more.

Does that PR require more verification?  I'm happy to test it locally, for example.

And, something I should have said originally... thanks for a great API!  It has allowed me to scan new additions to my library so I can do additional processing on them. :)

**Comment by phillipj** [comment]
Ahhhh thanks for the much needed reminder about that PR! Merged it now and aiming for publishing to npm ASAP.

My pleasure about the package. I'm still astonished it helps people out after 9 years, whereas the last handful or years has honestly been pretty stale 😄

**Comment by phillipj** [comment]
@MMeldrum v5.3.2 is now out on npm, please try it out and close this issue if it works as expected?

**Comment by MMeldrum** [comment]
I just upgraded and it worked perfectly. :)

Hard to believe the project is 9 years old. It must be nice to see it still proving useful after all this time. Thanks for still maintaining it.
