### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by chrishoage** [phillipj/node-plex-api#14]
On line [153 in api.js](https://github.com/phillipj/node-plex-api/blob/master/lib/api.js#L153) you pass in `this.options` when plex-api-credentails expects the PlexAPI object https://github.com/phillipj/node-plex-api-credentials/blob/master/index.js#L29

This causes an error because options does not exist on the options object and does not authenticate.

**Comment by phillipj** [comment]
Oh my, what a blooper! Thanks for pointing it out, I'll push a patch version right away.
