### ISSUE TITLE
access to X-Plex-Token

### ISSUE THREAD

**Issue by MikeOne** [phillipj/node-plex-api#16]
I would like to have access to the token after the signin process. I seems I can't get to it from the plex-api itself. Is there a possibility to add this token? I might a very smell change that actually add the token to the resolve in PlexAPI.prototype._authenticate. So line 163 - 164:

self.authToken = token;
deferred.resolve(token);

which actually allows me to call _authenticate myself on the plex-api instance. 

Is this an option?

**Comment by phillipj** [comment]
Hi!

As you have seen there's no easy / documented way to retrieve the token ATM. Looking at the code you should be able to do something like this:
```js
var PlexAPI = require('plex-api');

var client = new PlexAPI({
  username: 'foo',
  password: 'bar'
});

client.authenticator.on('token', function(token) {
  console.log('I haz the X-Plex token:', token);
});
```

As that requires deep insight into how this package works and is very tightly coupled, it's far for ideal. We could expose an authenticated event from the PlexAPI instance itself? E.g.
```js
// ..instantiate client as above

client.on('authenticated', function(token) {
  console.log('I haz the X-Plex token:', token);
});
```

Would that suffice for what you need?

**Comment by MikeOne** [comment]
Actually, if the first option already works, it would suffice for me. I've gone a bit more complex and included the plex-api-credentials module separately and are now using:

var PlexAuth = require('plex-api-credentials');
PlexAuth(config).authenticate(api, function(empty, token){
		console.log("token: " + token);
	});

but your first option seems much cleaner than this (and saves a dependancy) - so I'll try that.

**Comment by MikeOne** [comment]
Hmmm.. Maybe my option is actually better for me. As I can now use a promise in an actual method call instead of depending on an event that might come in at some time...  What I have works for what I need so great!

I have another issue I'm trying to resolve, it's unrelated to this issue, should I raise another issue or can we discuss here?

**Comment by MikeOne** [comment]
Just for your information, I'm on a larger team for a kickstarter project, specifically responsible for writing the Plex functionality. This kickstarter product will soon be in stores and I hope to use your module (non-forked) on this this app. The thing I'm writing will be open-source but installed on a physical device.

**Comment by phillipj** [comment]
Awesome that you found a solution to your issue 👍

Sounds like you could close this issue and open a new one for that second
issue.

**Comment by phillipj** [comment]
Wow that sounds exciting! So you have a link to that kickstarter?

**Comment by MikeOne** [comment]
Sure, it's called 'Homey' (https://www.kickstarter.com/projects/athom/homey-the-living-room-talk-to-your-home). It's pretty close to production now :-)

I'll open an new issue (maybe - I first have to check something..)

**Comment by OverloadUT** [comment]
Awesome project!

Feel free to check out my [alexa-plex](https://github.com/OverloadUT/alexa-plex) app if it could help at all, as it is functionally similar. I am also currently (as in yesterday and today) working on a PIN-based authentication module for node-plex-api here: [node-plex-api-pinauth](https://github.com/OverloadUT/node-plex-api-pinauth) (it's just placeholder code right now but I'm getting close locally)

**Comment by MikeOne** [comment]
Okay, that might be useful to me actually (PIN). Do you know why xml2js doesn't like the plex.tv responses btw? I can get raw xml back, but trying to convert it to a json object yields no usable object. I'm trying http://plex.tv/pms/friends/all

I get a valid xml response back:

<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer friendlyName="myPlex" identifier="com.plexapp.plugins.myplex" machineIdentifier="7895740153a34f074effd23a490674034887ca4c" totalSize="1" size="1">
  <User id="17574" title="<snip>" username="<snip>" email="p<snip>" recommendationsPlaylistId="f75b5fa8d2e851c1" thumb="https://secure.gravatar.com/avatar/d6ab8600f6676fd6e0d3ff6e5a08f01e?d=https%3A%2F%2Fplex.tv%2Favatars%2F8C8165%2F50%2F1">
    <Server id="35029" serverId="81349" machineIdentifier="<snip>" name="Mac Mini Media Machine" lastSeenAt="1440599096" numLibraries="4" owned="1"/>
    <Server id="1775097" serverId="355920" machineIdentifier="<snip>" name="Headquarters" lastSeenAt="1440563551" numLibraries="8" owned="0"/>
  </User>
</MediaContainer>

But if I pull it through xml2js, only this is left:

{ comment: '',
  sgmlDecl: '',
  textNode: '',
  tagName: '',
  doctype: '',
  procInstName: '',
  procInstBody: '',
  entity: '',
  attribName: '',
  attribValue: '',
  cdata: '',
  script: '',
  c: '',
  q: '',
  bufferCheckPosition: 65536,
  opt: 
   { trim: false,
     normalize: false,
     xmlns: false,
     lowercase: undefined },
  looseCase: 'toUpperCase',
  tags: [],
  sawRoot: false,
  closedRoot: false,
  closed: false,
  error: null,
  tag: null,
  strict: true,
  noscript: true,
  state: 0,
  strictEntities: undefined,
  ENTITIES: {},
  attribList: [],
  trackPosition: true,
  column: 0,
  line: 0,
  position: 0,
  errThrown: false,
  onerror: [Function],
  ended: true,
  onopentag: [Function],
  onclosetag: [Function],
  ontext: [Function],
  oncdata: [Function],
  startTagPosition: 838 } { object: true }

Any ideas? (removed sensitive data with <snip>)

**Comment by MikeOne** [comment]
No idea why github is truncating my comment..

**Comment by MikeOne** [comment]
anyway, github is screwing me now. valid XML, but after xml2js, I get 

{ comment: '',
  sgmlDecl: '',
  textNode: '',
  tagName: '',
  doctype: '',
  procInstName: '',
  procInstBody: '',
  entity: '',
  attribName: '',
  attribValue: '',
  cdata: '',
  script: '',
  c: '',
  q: '',
  bufferCheckPosition: 65536,
  opt: 
   { trim: false,
     normalize: false,
     xmlns: false,
     lowercase: undefined },
  looseCase: 'toUpperCase',
  tags: [],
  sawRoot: false,
  closedRoot: false,
  closed: false,
  error: null,
  tag: null,
  strict: true,
  noscript: true,
  state: 0,
  strictEntities: undefined,
  ENTITIES: {},
  attribList: [],
  trackPosition: true,
  column: 0,
  line: 0,
  position: 0,
  errThrown: false,
  onerror: [Function],
  ended: true,
  onopentag: [Function],
  onclosetag: [Function],
  ontext: [Function],
  oncdata: [Function],
  startTagPosition: 838 } { object: true }

So no data left from the original XML response.
Any ideas?

**Comment by MikeOne** [comment]
Basically, I'd love to be able to use the plex.tv endpoints as well, using plex-api, so basically:

(curConfig is a complete config with username and password etc):

curConfig.hostname = "plex.tv";
curConfig.port = "80";
var plexTV = new PlexAPI(curConfig);
plexTV.query("/pms/friends/all").then(function(result){
		console.log(result);
}) 

This would be a great feature for me..

**Comment by phillipj** [comment]
Just found a major bug in our code that turns XML into JSON. In summary it doesnt do callback and promises correctly, resulting in that wierd object @MikeOne posted as the resolved JSON.

If no one else jumps at this right away, I'll have a look at it in the start of next week :)

Closing this issue and creating a new issue.
