### ISSUE TITLE
Parsing XML doesnt work

### ISSUE THREAD

**Issue by phillipj** [phillipj/node-plex-api#17]
As reported by in #16 it might seem there's some issues with parsing XML into JSON when requesting plex.tv.

After some debugging I found the reason being we're not doing callback and promises corrently. This means especially these lines in `./lib/api.js`:

```js
if (response.headers['content-type'].indexOf('xml') > -1) {
  return deferred.resolve(xml2js.parseString(body.toString('utf8'), {
    object: true
  }));
}
```

The value being resolved is the return value from `xml2js.parseString()` which does not work as intended since `.parseString()` is async and will yield a callback when done.

**Comment by MikeOne** [comment]
This is what I used to get it working locally:    


    xml2js.parseString(body.toString('utf8'), { attrkey: 'attributes',  xmlns: true }, function(err, json) {
           return deferred.resolve(json);
    });

Not sure what the further logic is expecting as attrkey as I'm using my own (json) parser with the custom request to plex.tv I made.

**Comment by OverloadUT** [comment]
This is super bizarre - I don't know why my project would be working at all with such a fundamental issue present. I'll look in to this as well.

**Comment by phillipj** [comment]
And you do actually request some XML endpoints @OverloadUT?

**Comment by OverloadUT** [comment]
I could have sworn my requests were getting XML, but I just checked it and as it turns out, my requests are all returning JSON directly. That makes sense then!

**Comment by phillipj** [comment]
@YouriT I got the impression that PlexServer responds with XML on some endpoints in your PR #7. Do you remember which endpoints that was exactly?

**Comment by MikeOne** [comment]
@phillipj , once this fix has been implemented, do you think I would be in a position to have my application setup 3 instances of plexApi:

1) One to PMS
2) One to a client (usually on port 3005)
3) And a connection to plex.tv to do additional requests like getting shared servers (unless you know another way to address a shared server?).

plex.tv endpoints (like /devices.xml and /pms/friends/all and /pms/resources) all return just XML (I think). Am I correct in assuming that the current version does not support these calls but an updated version (with the correct XML parsing) will?

Maybe this is not the correct place to pick your brain on this. I'd love to be able to chat with some core developers to discuss some of the scenarios I'm trying to solve (one of which being able to get media from a shared server for example). Are there any channels I could use to have a quick chat with either you or maybe @OverloadUT ?

**Comment by YouriT** [comment]
@phillipj I think that I add XML when asked for details about files but cannot remember the endpoint unfortunately. I can try to find it back if you need?

**Comment by phillipj** [comment]
@YouriT yes please :+1:

**Comment by phillipj** [comment]
@MikeOne having 3 instances should be no problem. Yes, you are correct v3.1.1 doesnt support XML at all ATM due to a big bug in XML transformation. A patch version will be released which fixes this issue.

IMO the first priority would be to support XML from PMS endpoints. I'm curious about the format of that XML and whether or not we should (a) just convert it to JSON or (b) do some transformation aswell to have it look like what we get from JSON endpoints. Would love some feedback about this!

Landing that discussion is crucial before considering plex.tv requests. After all this package was created for requesting PMS and should keep that focus going forward; doing **one** thing and do it well. If the format from plex.tv differs from the XML from PMS, I would say a separate package exlusively for plex.tv should be created.

Just created a separate issue addressing plex.tv requests #19.

**Comment by OverloadUT** [comment]
@MikeOne it is actually possible to do Client requests as part of the same PMS server connection. This is how I do it in my Amazon Echo Plex app. Inspiration for this came from phillipj/node-plex-control, which gave me the building blocks for how to have all client requests handled by a PMS. For my app 

To do custom plex.tv requests though, I agree with @phillipj that it might be best for a separate (add-on?) module to handle direct plex.tv requests.

I've actually been thinking about writing a module that does a bit of abstraction on top of node-plex-api. By simply providing user+pass (or an auth token) you should be able to get the list of servers from plex.tv, including the hostname and port, to ease the burden of the end-developer needing to do that himself. I will probably need this for v2 or v3 of my Echo app anyway.

**Comment by OverloadUT** [comment]
@MikeOne regarding a way to chat, I just set up a Gitter for this project. Feel free to reach out there :) https://gitter.im/phillipj/node-plex-api

**Comment by YouriT** [comment]
@phillipj it was when adding "?checkFiles=1" to an entity, it was mixing XML and JSON in the response, quite awkward behaviour btw. Don't know if it still does have this behaviour because my project is not running on for now, didn't have time to finish it.

**Comment by phillipj** [comment]
:+1: @YouriT for replying

**Comment by MikeOne** [comment]
Updated to 3.1.2 - XML worked straight away in my app - thanks!

**Comment by phillipj** [comment]
Wooohooo 🎉
