### ISSUE TITLE
Requesting plex.tv

### ISSUE THREAD

**Issue by phillipj** [phillipj/node-plex-api#19]
@MikeOne has recently expressed the need to use this package to request plex.tv aswell in #17. This issue should be used to discuss why that is a good idea and whether or not we should support it in core.

Seems like others have more experience than me on the subject, as the only thing I've been doing so far is authentication.

Especially what parts are useful from `plex-api` while requesting plex.tv? Is it the majority of features we've got already (GET and POST requests, authentication ++ or is it mainly the X-Plex header generation?

**Comment by OverloadUT** [comment]
The main reason I will want to do more plex.tv requests in the future will be for the `/servers` request, which can give you a list of active PMS servers and how to contact them. This will remove the need to keep the hostname and port in the app's configuration (or database). This will be especially useful for apps that live outside of the PMS's local network, due to the fact that the automatically-opened port can change when the PMS restarts.

**Comment by phillipj** [comment]
The `/servers` endpoint sounds really helpful!

Found some info about plex.tv endpoints in the unofficial plex docs which might be useful in this discussion: https://code.google.com/p/plex-api/wiki/PlexTv

**Comment by MikeOne** [comment]
Yes it is helpful! It's actually /pms/servers.xml now (I think it changed). Another very useful one is /pms/resources.xml - gives much more detailed information than servers.xml

**Comment by phillipj** [comment]
@MikeOne after you have been playing with plex.tv requests for a while, it would be really nice to hear what parts of plex-api you're actually using against plex.tv. E.g. is it only `query()` and authentication handling or more?

**Comment by MikeOne** [comment]
Authentication (manual - in order to fetch a token on demand) - postQuery -> to handle PIN auth (implementing that now, stealing some ideas from @OverloadUT ;-) but also the other plex.tv endpoints are pretty useful like /pms/devices.xml

**Comment by phillipj** [comment]
Alright, my understanding of this so far is that it turns out plex-api could be pretty useful while requesting plex.tv, and doesnt need specific plex.tv functionality ATM.

Closing this issue, feel free to re-open it if something comes up in the future.
