### ISSUE TITLE
Node Plex API use

### ISSUE THREAD

**Issue by adelatour11** [phillipj/node-plex-api#22]
Hello

i've just discover your work and i would like to understand the way it works : I have an android plex app that can connec to a plex home theater to stream music. Is it possible to cast music or video from an android plex app to the node server ?

how is managed the audio or video output ?

**Comment by phillipj** [comment]
Hi there!

To be honest, I have never ventured out trying to stream anything. Personally only used the server HTTP API to discover which photos, music, TV series and movies I've got. Aswell as simple client controlling such as pause, play etc which I extracted into its own package [plex-control](https://github.com/phillipj/node-plex-control).

You may find some hints about what you are looking for in the [unofficial Plex API docs](https://code.google.com/p/plex-api/w/list).

**Comment by phillipj** [comment]
I would have asked in one of the [Plex Forums](https://forums.plex.tv/). Atleast whether or not streaming via the HTTP API is actually possible, as that's not really a node.js / plex-api issue in the first place. If you get any advice about streaming in the forums, we would happily help you get started with the node.js side of things.

Closing this for now.
