### ISSUE TITLE
Timeout Option

### ISSUE THREAD

**Issue by lokenx** [phillipj/node-plex-api#58]
Any thoughts about adding a timeout option, or even hard coding one? Not sure what the default is for the request library but it's on the long side.

**Comment by phillipj** [comment]
Atleast having the ability to provide sn explicit timeout sounds like a
very good idea 👍

**Comment by lokenx** [comment]
Hey @phillipj any idea why this test is failing for timeouts?

[Here](https://github.com/lokenx/node-plex-api/blob/master/test/server.js#L93) I've added a server test that has a delay added, and test it [here](https://github.com/lokenx/node-plex-api/blob/master/test/timeout-test.js) but Nock complains that [Delay](https://github.com/node-nock/nock#delay-the-response) isn't a function for some reason.

Any insight :confused: ?

**Comment by lokenx** [comment]
Fixed it I believe! Just writing that comment helped haha

https://github.com/phillipj/node-plex-api/pull/60

**Comment by phillipj** [comment]
Closing this as you resolved it yourself in #60 :)
