### ISSUE TITLE
Dicover Plex servers?

### ISSUE THREAD

**Issue by FezVrasta** [phillipj/node-plex-api#69]
Hi, 

is there a way to automatically discover local Plex servers?

**Comment by phillipj** [comment]
Could https://github.com/phillipj/node-plex-api/issues/19#issuecomment-136475879 be what you're looking for?

**Comment by FezVrasta** [comment]
I'm not sure... I'd just like to get a list of Plex server's addresses on the local network.

**Comment by phillipj** [comment]
Not that I'm aware of, no. Have you tried asking on the [plex forums](https://forums.plex.tv/), or possibly other Plex server clients like https://github.com/drzoidberg33/plexpy or https://github.com/plexinc/plex-media-player ?

**Comment by phillipj** [comment]
Closing this for now cause no one seems to have a reasonable approach to do this, in this project at least.

**Comment by Glavin001** [comment]
For those interested, here is what works today for me:

```javascript
const PlexAPI = require("plex-api");
const client = new PlexAPI({ hostname: 'plex.tv', port: 443, username: "USERNAME", password: "PASSWORD" });
client.query('/pms/servers.xml')
  .then(result => console.log(JSON.stringify(result, null, 2)))
  .catch(error => console.error(error));
```

Hope that helps others get started!

**Comment by phillipj** [comment]
@Glavin001 thanks for sharing your solution, much appreciated! 👍
