### ISSUE TITLE
Plex server's events

### ISSUE THREAD

**Issue by gpapin** [phillipj/node-plex-api#73]
Is it possible to wait for an event like : play or pause and perform action accordingly using this lib ?

**Comment by phillipj** [comment]
As far as I know, it's not possible to get such events pushed to your code by the Plex server. You could of course do some periodic polling, but you won't get *actual real time* updates that way.

**Comment by gpapin** [comment]
Hmm I feared you'd say that :( 

I come from Kodi/xbmc and they expose such api with websocket support, this is really useful when you need to be responsive. I'll probably post something on their forum, they must have something available for their clients that I might be able to use.

I was planning on changing the lights status on the rooms based on the playback, this is why I need to have the smallest delay possible.

Thanks anyway !
