### ISSUE TITLE
New sessionKey on stop command?

### ISSUE THREAD

**Issue by Swiftnesses** [phillipj/node-plex-api#80]
Hi Guys,

Under some circumstances I'm seeing a new sessionKey being issued on a stop command. This happens for example when starting something via Safari, letting it play for a second or two and then dragging the seek to the end and letting it stop.

I see this in my debug:

`WEBSOCKET] Detected session:
[ { sessionKey: '89',
    guid: '',
    ratingKey: '23362',
    url: '',
    key: '/library/metadata/23362',
    viewOffset: 5672758,
    state: 'paused',
    transcodeSession: 'vkxjl3ya6ig6mdkf9gear7ta' } ]`

THEN straight after:

`[WEBSOCKET] Detected session:
[ { sessionKey: '90',
    guid: '',
    ratingKey: '23362',
    url: '',
    key: '/library/metadata/23362',
    viewOffset: 5672758,
    state: 'stopped' } ]`

I use the sessionKey to keep track of player status, hence this is causing me a nightmare :(

**Comment by phillipj** [comment]
To break the silence; I've got no experience with `sessionKey` unfortunately.

Have you tried asking on the Plex/dev forum? https://forums.plex.tv/categories/channel-development

**Comment by phillipj** [comment]
Due to no response from others or the original poster, I'll close this issue. Feel free to re-open if needed.
