### ISSUE TITLE
Accessing Plex Artwork 

### ISSUE THREAD

**Issue by 8bitgentleman** [phillipj/node-plex-api#87]
I'm not sure if this is a good place to ask this question but I'm having some difficulty with the plex api.
I've been trying to access and display artwork from an item in my plex library. The "art" and "thumb" tag in the plex MediaContainer object both return a buffer of, I assume, some kind of jpeg data. How do I display that data as an image?

**Comment by phillipj** [comment]
Haven't done any thumb work myself, but from what you described it might be worth a shot creating an inline .png image from a `Buffer` with the [datauri package](https://www.npmjs.com/package/datauri#from-a-buffer)?

**Comment by 8bitgentleman** [comment]
Worked like a charm, thanks @phillipj !
