### ISSUE TITLE
webpack + node-plex-api 

### ISSUE THREAD

**Issue by jagDanJu** [phillipj/node-plex-api#88]
Hey,

i´am using this api + webpack and get the following error:

`Module not found: Error: Can't resolve 'net'`

and 

```
ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls'
```
Does anyone have an idea?

Thanks.

**Comment by phillipj** [comment]
Sorry for the extremely delayed response!

Could you please elaborate more around what you're trying to do?

My first thought is that it seems you're trying to use this plex-api package in a browser environment. If I've understood that correctly, I'm sure you'll meet quite a lot of challenges along the way, as this package has been made with Node.js in mind, not browsers. To be honest I've never even thought about what it would take to make this browser compliant.

**Comment by phillipj** [comment]
Closing this for now. I know there are some creative ways around mocking Node.js environment in browsers you might want to look into. Any contributions making this package more browser friendly would also be much appreciated.
