### ISSUE TITLE
How do I get a streaming url?

### ISSUE THREAD

**Issue by jimmywarting** [phillipj/node-plex-api#90]
How would i get a stream url (perhaps dash) from using this api after i have authorised using a pin?

**Comment by au5ton** [comment]
This is almost a year old, but if anyone comes across this, I think this will work.

See: `/video/:/transcode/universal/start.m3u8`
https://github.com/Arcanemagus/plex-api/wiki/Plex-Web-API-Overview

**Comment by phillipj** [comment]
Closing this for now. If anyone else has got any other tips, don't hesitate to share them.
